2017-01-14 19:53:35 Error: Fatal Error (1): Class 'AppController' not found in [C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php, line 10]
Request URL: /app_name/usuarios/index.ctp
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-01-14 19:53:36 Error: [Cake\Error\FatalErrorException] Class 'AppController' not found
Request URL: /app_name/usuarios/index.ctp
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'AppContr...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-01-14 19:55:33 Error: Fatal Error (1): Class 'AppController' not found in [C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php, line 10]
Request URL: /app_name/usuarios/index.ctp
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-01-14 19:55:34 Error: [Cake\Error\FatalErrorException] Class 'AppController' not found
Request URL: /app_name/usuarios/index.ctp
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'AppContr...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-01-14 19:56:15 Error: Fatal Error (1): Class 'AppController' not found in [C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php, line 10]
Request URL: /app_name/usuarios/index.ctp
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-01-14 19:56:15 Error: [Cake\Error\FatalErrorException] Class 'AppController' not found
Request URL: /app_name/usuarios/index.ctp
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'AppContr...', 'C:\\xampp\\htdocs...', 10)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-01-14 19:58:05 Error: [Cake\Controller\Exception\MissingActionException] Action UsuariosController::index.ctp() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsuariosController',
  'action' => 'index.ctp',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /usuarios/index.ctp
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsuariosController))
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(93): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#13 {main}


2017-01-14 20:04:09 Error: [Cake\Controller\Exception\MissingActionException] Action UsuariosController::index.ctp() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsuariosController',
  'action' => 'index.ctp',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /usuarios/index.ctp
Stack Trace:
#0 C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php(78): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(121): App\Controller\UsuariosController->invokeAction()
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsuariosController))
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(93): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#13 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#14 {main}


2017-01-14 20:29:27 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Vendor could not be found.
Exception Attributes: array (
  'class' => 'Vendor',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /vendor/cakephp/bake/src/Shell/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(72): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#13 {main}


2017-01-14 20:43:51 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Src could not be found.
Exception Attributes: array (
  'class' => 'Src',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /src/Shell/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(72): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#13 {main}


2017-01-14 20:44:30 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Shell could not be found.
Exception Attributes: array (
  'class' => 'Shell',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /Shell/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(72): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#13 {main}


2017-01-14 20:44:47 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php, line 25]
Request URL: /app_name/Usuarios/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-01-14 20:44:47 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /app_name/Usuarios/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 25)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-01-14 20:46:53 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php, line 24]
Request URL: /app_name/Usuarios/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-01-14 20:46:54 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /app_name/Usuarios/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-01-14 22:49:07 Error: [Cake\View\Exception\MissingTemplateException] Template file "Usuarios\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Usuarios\\index.ctp',
)
Request URL: /Usuarios/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\View\View.php(593): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Controller\Controller.php(604): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(127): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsuariosController))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#13 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#14 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-01-14 22:50:19 Error: [Cake\View\Exception\MissingTemplateException] Template file "Usuarios\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Usuarios\\index.ctp',
)
Request URL: /Usuarios/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\View\View.php(593): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Controller\Controller.php(604): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(127): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsuariosController))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#13 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#14 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-01-14 22:52:45 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\app_name\src\Template\Usuarios\index.ctp, line 11]
Request URL: /app_name/Usuarios/
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
include - APP/Template\Usuarios\index.ctp, line 11
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1014
Cake\View\View::_render() - CORE\src\View\View.php, line 973
Cake\View\View::render() - CORE\src\View\View.php, line 597
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 604
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 127
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 95
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 62
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 81
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 90
[main] - ROOT\webroot\index.php, line 37



2017-01-14 22:59:49 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\app_name\src\Template\Usuarios\index.ctp, line 11]
Request URL: /app_name/Usuarios/
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
include - APP/Template\Usuarios\index.ctp, line 11
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1014
Cake\View\View::_render() - CORE\src\View\View.php, line 973
Cake\View\View::render() - CORE\src\View\View.php, line 597
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 604
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 127
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 95
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 62
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 81
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 90
[main] - ROOT\webroot\index.php, line 37



2017-01-14 22:59:53 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\app_name\src\Template\Usuarios\index.ctp, line 11]
Request URL: /app_name/Usuarios/
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
include - APP/Template\Usuarios\index.ctp, line 11
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1014
Cake\View\View::_render() - CORE\src\View\View.php, line 973
Cake\View\View::render() - CORE\src\View\View.php, line 597
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 604
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 127
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 95
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 62
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 81
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 90
[main] - ROOT\webroot\index.php, line 37



2017-01-14 23:00:15 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php, line 24]
Request URL: /app_name/Usuarios/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-01-14 23:00:16 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /app_name/Usuarios/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-01-14 23:00:49 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php, line 24]
Request URL: /app_name/Usuarios/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-01-14 23:00:50 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /app_name/Usuarios/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-01-14 23:03:22 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php, line 24]
Request URL: /app_name/Usuarios/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-01-14 23:03:23 Warning: Headers already sent in C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php:24
2017-01-14 23:03:23 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /app_name/Usuarios/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-01-14 23:03:41 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php, line 24]
Request URL: /app_name/Usuarios/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-01-14 23:03:43 Warning: Headers already sent in C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php:24
2017-01-14 23:03:43 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /app_name/Usuarios/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-01-14 23:04:19 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php, line 24]
Request URL: /app_name/Usuarios/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-01-14 23:04:20 Warning: Headers already sent in C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php:24
2017-01-14 23:04:20 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /app_name/Usuarios/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-01-14 23:06:50 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php, line 24]
Request URL: /app_name/Usuarios/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-01-14 23:06:51 Warning: Headers already sent in C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php:24
2017-01-14 23:06:51 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /app_name/Usuarios/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-01-14 23:08:40 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php, line 24]
Request URL: /app_name/Usuarios/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-01-14 23:08:41 Warning: Headers already sent in C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php:24
2017-01-14 23:08:41 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /app_name/Usuarios/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-01-14 23:10:10 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php, line 24]
Request URL: /app_name/Usuarios/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-01-14 23:10:11 Warning: Headers already sent in C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php:24
2017-01-14 23:10:11 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /app_name/Usuarios/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-01-14 23:12:52 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php, line 24]
Request URL: /app_name/Usuarios/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-01-14 23:12:54 Warning: Headers already sent in C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php:24
2017-01-14 23:12:54 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /app_name/Usuarios/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-01-14 23:13:39 Error: Fatal Error (1): Call to a member function find() on boolean in [C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php, line 24]
Request URL: /app_name/Usuarios/
Referer URL: http://localhost/app_name/
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 216
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 98
[main] - [internal], line ??



2017-01-14 23:13:40 Warning: Headers already sent in C:\xampp\htdocs\app_name\src\Controller\UsuariosController.php:24
2017-01-14 23:13:40 Error: [Cake\Error\FatalErrorException] Call to a member function find() on boolean
Request URL: /app_name/Usuarios/
Referer URL: http://localhost/app_name/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(98): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-01-14 23:14:21 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Usuarios could not be found.
Exception Attributes: array (
  'class' => 'Usuarios',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /Usuarios/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(72): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#13 {main}


2017-01-14 23:14:27 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Usuario could not be found.
Exception Attributes: array (
  'class' => 'Usuario',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /Usuario/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(72): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#13 {main}


2017-01-14 23:14:52 Error: [Cake\Database\Exception] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cakeprojeto.usuario' doesn't exist
Request URL: /Usuario/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Database\Schema\Collection.php(97): Cake\Database\Schema\Collection->_reflect('Column', 'usuario', Array, Object(Cake\Database\Schema\Table))
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Database\Schema\CachedCollection.php(63): Cake\Database\Schema\Collection->describe('usuario', Array)
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\ORM\Table.php(440): Cake\Database\Schema\CachedCollection->describe('usuario')
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\ORM\Query.php(210): Cake\ORM\Table->schema()
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\ORM\Query.php(167): Cake\ORM\Query->addDefaultTypes(Object(Cake\ORM\Table))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\ORM\Table.php(1336): Cake\ORM\Query->__construct(Object(Cake\Database\Connection), Object(Cake\ORM\Table))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\ORM\Table.php(964): Cake\ORM\Table->query()
#7 C:\xampp\htdocs\app_name\src\Controller\UsuarioController.php(24): Cake\ORM\Table->find('users')
#8 [internal function]: App\Controller\UsuarioController->index()
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Controller\Controller.php(431): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsuarioController))
#12 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#15 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#16 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#17 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#18 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#19 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#20 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#21 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#22 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#23 {main}


2017-01-14 23:23:46 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Usuarios could not be found.
Exception Attributes: array (
  'class' => 'Usuarios',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /Usuarios/
Referer URL: http://localhost/app_name/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(72): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#13 {main}


2017-01-14 23:24:05 Error: [BadMethodCallException] Unknown finder method "users"
Request URL: /Usuario/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\ORM\Table.php(967): Cake\ORM\Table->callFinder('users', Object(Cake\ORM\Query), Array)
#1 C:\xampp\htdocs\app_name\src\Controller\UsuarioController.php(24): Cake\ORM\Table->find('users')
#2 [internal function]: App\Controller\UsuarioController->index()
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Controller\Controller.php(431): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsuarioController))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#13 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#15 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#16 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#17 {main}


2017-01-14 23:24:30 Error: [Cake\View\Exception\MissingTemplateException] Template file "Usuario\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Usuario\\index.ctp',
)
Request URL: /Usuario/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\View\View.php(593): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Controller\Controller.php(604): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(127): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsuarioController))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#13 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#14 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-01-15 16:11:07 Error: [Cake\View\Exception\MissingTemplateException] Template file "Usuario\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Usuario\\index.ctp',
)
Request URL: /Usuario/
Referer URL: http://localhost/app_name/index.php?XDEBUG_SESSION_START=netbeans-xdebug
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\View\View.php(593): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Controller\Controller.php(604): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(127): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsuarioController))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#13 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#14 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-01-15 16:22:07 Error: [Cake\View\Exception\MissingTemplateException] Template file "Usuario\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Usuario\\index.ctp',
)
Request URL: /Usuario/
Referer URL: http://localhost/app_name/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\View\View.php(593): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Controller\Controller.php(604): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(127): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsuarioController))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#13 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#14 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-01-15 16:23:38 Error: [BadMethodCallException] Unknown method "create"
Request URL: /usuario/adicionar
Referer URL: http://localhost/app_name/usuario/adicionar
Stack Trace:
#0 C:\xampp\htdocs\app_name\src\Controller\UsuarioController.php(32): Cake\ORM\Table->__call('create', Array)
#1 C:\xampp\htdocs\app_name\src\Controller\UsuarioController.php(32): Cake\ORM\Table->create()
#2 [internal function]: App\Controller\UsuarioController->adicionar()
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Controller\Controller.php(431): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsuarioController))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#13 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#15 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#16 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#17 {main}


2017-01-15 16:25:45 Error: [BadMethodCallException] Unknown method "create"
Request URL: /usuario/adicionar
Referer URL: http://localhost/app_name/usuario/adicionar
Stack Trace:
#0 C:\xampp\htdocs\app_name\src\Controller\UsuarioController.php(32): Cake\ORM\Table->__call('create', Array)
#1 C:\xampp\htdocs\app_name\src\Controller\UsuarioController.php(32): Cake\ORM\Table->create()
#2 [internal function]: App\Controller\UsuarioController->adicionar()
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Controller\Controller.php(431): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\UsuarioController))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#13 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#15 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#16 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#17 {main}


2017-01-15 16:54:01 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Vendor could not be found.
Exception Attributes: array (
  'class' => 'Vendor',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /vendor/
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(72): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#13 {main}


2017-01-15 16:55:48 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Vendor could not be found.
Exception Attributes: array (
  'class' => 'Vendor',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /vendor/cakephp/bake/src/Shell/BakeShell.php
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(72): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(93): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#13 {main}


2017-01-15 17:00:07 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Vendor could not be found.
Exception Attributes: array (
  'class' => 'Vendor',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /vendor/cakephp/bake/src/Shell/BakeShell.php
Stack Trace:
#0 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(72): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(93): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\app_name\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\app_name\webroot\index.php(37): Cake\Http\Server->run()
#13 {main}


2017-01-15 17:36:51 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Src could not be found.
Exception Attributes: array (
  'class' => 'Src',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /src/Shell/ConsoleShell.php
Stack Trace:
#0 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(72): Cake\Http\ControllerFactory->missingController(Object(Cake\Network\Request))
#1 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(92): Cake\Http\ControllerFactory->create(Object(Cake\Network\Request), Object(Cake\Network\Response))
#2 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(93): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\cake_blog\webroot\index.php(37): Cake\Http\Server->run()
#13 {main}


2017-01-15 18:10:08 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::view() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'view',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /articles/view/1
Referer URL: http://localhost/cake_blog/Articles/
Stack Trace:
#0 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\cake_blog\webroot\index.php(37): Cake\Http\Server->run()
#13 {main}


2017-01-15 18:18:07 Error: [Cake\View\Exception\MissingTemplateException] Template file "Articles\view.ctp" is missing.
Exception Attributes: array (
  'file' => 'Articles\\view.ctp',
)
Request URL: /articles/view/3
Referer URL: http://localhost/cake_blog/Articles/
Stack Trace:
#0 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\View\View.php(593): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Controller\Controller.php(604): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(127): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ArticlesController))
#4 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#13 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#14 C:\xampp\htdocs\cake_blog\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-01-15 19:02:15 Error: [Cake\Datasource\Exception\InvalidPrimaryKeyException] Record not found in table "articles" with primary key [NULL]
Request URL: /articles/view/
Stack Trace:
#0 C:\xampp\htdocs\cake_blog\src\Controller\ArticlesController.php(23): Cake\ORM\Table->get(NULL)
#1 [internal function]: App\Controller\ArticlesController->view()
#2 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Controller\Controller.php(431): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#4 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ArticlesController))
#5 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#7 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#8 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#9 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#10 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#11 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#13 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#14 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#15 C:\xampp\htdocs\cake_blog\webroot\index.php(37): Cake\Http\Server->run()
#16 {main}


2017-01-15 19:02:43 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::edit() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'edit',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /articles/edit/1
Referer URL: http://localhost/cake_blog/articles/
Stack Trace:
#0 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\cake_blog\webroot\index.php(37): Cake\Http\Server->run()
#13 {main}


2017-01-15 19:14:15 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::add() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'add',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /articles/add
Referer URL: http://localhost/cake_blog/articles/
Stack Trace:
#0 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(121): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#5 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#12 C:\xampp\htdocs\cake_blog\webroot\index.php(37): Cake\Http\Server->run()
#13 {main}


2017-01-15 19:14:38 Error: [Cake\View\Exception\MissingTemplateException] Template file "Articles\adicionar.ctp" is missing.
Exception Attributes: array (
  'file' => 'Articles\\adicionar.ctp',
)
Request URL: /articles/adicionar
Referer URL: http://localhost/cake_blog/articles/
Stack Trace:
#0 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\View\View.php(593): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Controller\Controller.php(604): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(127): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ArticlesController))
#4 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#13 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#14 C:\xampp\htdocs\cake_blog\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-01-15 19:15:19 Error: [Cake\View\Exception\MissingTemplateException] Template file "Articles\adicionar.ctp" is missing.
Exception Attributes: array (
  'file' => 'Articles\\adicionar.ctp',
)
Request URL: /articles/adicionar
Stack Trace:
#0 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\View\View.php(593): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Controller\Controller.php(604): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(127): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ArticlesController))
#4 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#13 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#14 C:\xampp\htdocs\cake_blog\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-01-15 19:16:01 Error: [Cake\View\Exception\MissingTemplateException] Template file "Articles\adicionar.ctp" is missing.
Exception Attributes: array (
  'file' => 'Articles\\adicionar.ctp',
)
Request URL: /articles/adicionar
Referer URL: http://localhost/cake_blog/articles
Stack Trace:
#0 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\View\View.php(593): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Controller\Controller.php(604): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(127): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ArticlesController))
#4 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#13 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#14 C:\xampp\htdocs\cake_blog\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-01-15 19:16:46 Warning: Warning (4096): Argument 1 passed to App\Model\Table\ArticlesTable::validationDefault() must be an instance of App\Model\Table\Validator, instance of Cake\Validation\Validator given, called in C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Validation\ValidatorAwareTrait.php on line 108 and defined in [C:\xampp\htdocs\cake_blog\src\Model\Table\ArticlesTable.php, line 13]
Request URL: /cake_blog/articles/adicionar
Referer URL: http://localhost/cake_blog/articles
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 146
App\Model\Table\ArticlesTable::validationDefault() - APP/Model\Table\ArticlesTable.php, line 13
Cake\ORM\Table::validator() - CORE\src\Validation\ValidatorAwareTrait.php, line 108
Cake\View\Form\EntityContext::_getValidator() - CORE\src\View\Form\EntityContext.php, line 463
Cake\View\Form\EntityContext::isRequired() - CORE\src\View\Form\EntityContext.php, line 406
Cake\View\Helper\FormHelper::_magicOptions() - CORE\src\View\Helper\FormHelper.php, line 1268
Cake\View\Helper\FormHelper::_parseOptions() - CORE\src\View\Helper\FormHelper.php, line 1167
Cake\View\Helper\FormHelper::input() - CORE\src\View\Helper\FormHelper.php, line 1013
include - APP/Template\Articles\adicionar.ctp, line 4
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 1014
Cake\View\View::_render() - CORE\src\View\View.php, line 973
Cake\View\View::render() - CORE\src\View\View.php, line 597
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 604
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 127
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 95
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 83
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 62
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 81
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 90
[main] - ROOT\webroot\index.php, line 37



2017-01-15 19:19:21 Error: [Cake\View\Exception\MissingTemplateException] Template file "Articles\editar.ctp" is missing.
Exception Attributes: array (
  'file' => 'Articles\\editar.ctp',
)
Request URL: /articles/editar/4
Referer URL: http://localhost/cake_blog/articles
Stack Trace:
#0 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\View\View.php(593): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Controller\Controller.php(604): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(127): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(95): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ArticlesController))
#4 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\BaseApplication.php(83): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(62): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#7 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#9 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(81): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#11 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#13 C:\xampp\htdocs\cake_blog\vendor\cakephp\cakephp\src\Http\Server.php(90): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response))
#14 C:\xampp\htdocs\cake_blog\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


